# Change these first
owner: jimwib # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Staak
    url: https://www.staak.co.uk
  - name: Bleeding Edge
    url: https://bleedingedge.com
  - name: Bleeding Edge Forums
    url: https://forum.bleedingedge.com
  - name: Johnson Gibbs
    url: https://johnsongibbs.co.uk
  - name: Ninja Theory
    url: https://ninjatheory.com
  - name: Ninja Theory WWW
    url: https://www.ninjatheory.com
  - name: Ninja Theory Api
    url: https://api.ninjatheory.com
  - name: Audiologic
    url: https://www.audiologic.co.uk/news-and-insights
  - name: Audiologic ie
    url: https://www.audiologic.ie/news-and-insights
  - name: Audiologic api
    url: https://admin.audiologic.co.uk/api/articles
  - name: Bleeding Edge CMS
    url: https://production-bleedingedge-cms.azurewebsites.net
  - name: Senuas Saga Home
    url: https://senuassaga.com
  - name: Senuas Saga News
    url: https://senuassaga.com/news
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
